#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running terraform fmt..."
cd infrastructure || exit 1
terraform fmt -check -recursive

echo "Running terraform validate..."
terraform validate

echo "Running tflint..."
tflint